import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;

public class ShortcutDialogNew extends DialogWrapper {
    private JTextField textField1;
    private JPanel panel1;

    protected ShortcutDialogNew(@Nullable Project project, boolean canBeParent) {
        super(project, canBeParent);
    }

    @Nullable
    @Override
    protected JComponent createCenterPanel() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        textField1 = new JTextField();
        panel1.add(textField1, "Card1");
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel1.add(label1, "Card2");
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        panel1.add(label2, "Card3");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
